AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-backend-t-ai

  Sample SAM Template for lambda-backend-t-ai

Parameters:
  StorageBucketName:
    Type: String
    Description: Name of the S3 bucket where data is stored
    Default: trainicity-ai-storage-bucket
  MainTableName:
    Type: String
    Description: Name of the DynamoDB table
    Default: trainicity-ai-main-table
Resources:
  AWSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: "aws-layer"
      Description: "A layer that contains shared code and libraries for aws services"
      ContentUri: "layers/aws-layer/"
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
  LLMLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: "llm-layer"
      Description: "A layer that contains shared code and libraries for language model services"
      ContentUri: "layers/llm-layer/"
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
  HandleGetThread:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleGetThread
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
              Resource: !ImportValue TrainicityAIMainTableArn
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref MainTableName
      Events:
        GetThreadAPIEvent:
          Type: Api
          Properties:
            Path: /getThread
            Method: ANY
  HandleUploadFile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleUploadFile
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          STORAGE_BUCKET_NAME: !Ref StorageBucketName
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !ImportValue TrainicityAIMainTableArn
            # Policy for trainicity-ai-storage-bucket
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !ImportValue TrainicityAIStorageBucketArn
      Events:
        UploadFileAPIEvent:
          Type: Api
          Properties:
            Path: /uploadFile
            Method: ANY
  HandleListThreads:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleListThreads
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !ImportValue TrainicityAIMainTableArn
      Events:
        ListThreadsAPIEvent:
          Type: Api
          Properties:
            Path: /listThreads
            Method: ANY
  HandleUpdateThread:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleUpdateThread
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !ImportValue TrainicityAIMainTableArn
      Events:
        UpdateThreadAPIEvent:
          Type: Api
          Properties:
            Path: /updateThread
            Method: ANY
  HandleDeleteFile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleDeleteFile
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          STORAGE_BUCKET_NAME: !Ref StorageBucketName
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !ImportValue TrainicityAIMainTableArn
            # Policy for trainicity-ai-storage-bucket
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource: !ImportValue TrainicityAIStorageBucketArn
      Events:
        DeleteFileAPIEvent:
          Type: Api
          Properties:
            Path: /deleteFile
            Method: ANY
  HandleDeleteThread:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleDeleteThread
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          STORAGE_BUCKET_NAME: !Ref StorageBucketName
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: !ImportValue TrainicityAIMainTableArn
            # Policy for trainicity-ai-storage-bucket
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource: !ImportValue TrainicityAIStorageBucketArn
      Events:
        DeleteThreadAPIEvent:
          Type: Api
          Properties:
            Path: /deleteThread
            Method: ANY
  HandleUpdateThreadTitle:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleUpdateThreadTitle
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !ImportValue TrainicityAIMainTableArn
      Events:
        UpdateThreadTitleAPIEvent:
          Type: Api
          Properties:
            Path: /updateThreadTitle
            Method: ANY
  HandleUpdateThreadUrls:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleUpdateThreadUrls
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
      Environment:
        Variables:
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !ImportValue TrainicityAIMainTableArn
      Events:
        UpdateThreadTitleAPIEvent:
          Type: Api
          Properties:
            Path: /updateThreadUrls
            Method: ANY
  HandleLLMStandardChat:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleLLMStandardChat
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
        - !Ref LLMLayer
  HandleLLMDocQAChat:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/handleLLMDocQAChat
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Architectures:
        - x86_64
      Layers:
        - !Ref AWSLayer
        - !Ref LLMLayer
      Environment:
        Variables:
          STORAGE_BUCKET_NAME: !Ref StorageBucketName
          MAIN_TABLE_NAME: !Ref MainTableName
      Policies:
        - Statement:
            # Policy for trainicity-ai-main-table
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !ImportValue TrainicityAIMainTableArn
            # Policy for trainicity-ai-storage-bucket
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !ImportValue TrainicityAIStorageBucketArn
